import Head from "next/head";
import Layouts from "../components/Layouts";
import Carousel from "react-bootstrap/Carousel";
import { FaStar } from "react-icons/fa";
import Image from "next/image";

export default function Home() {
  return (
    <div className="relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <Layouts>
        <div className="bg_img"></div>
        <Carousel indicators={false}>
          <Carousel.Item>
            <div className="carousel_wrapping">
              <div className="carousel_grid container mx-auto">
                <div className="text-white gap-y-5 flex flex-col">
                  <div className="desc_genres">
                    <span>SCI-FI</span>
                    <span>ADVENTURE</span>
                    <span>ACTION</span>
                  </div>
                  <div>
                    <h1 className="text-6xl">
                      GUARDIAN OF THE GALAXY <span className="text-4xl font-light font-['revert']">2015</span>
                    </h1>
                  </div>
                  <div className="flex items-center text-xl font-sans">
                    <FaStar className="text-yellow-300 mr-2" /> 7.4/10
                  </div>
                  <div>
                    <button className="button_full font-medium">WATCH TRAILER</button>
                  </div>
                </div>
                <div className="flex justify-end">
                  <Image src="/akame.jpg" alt="movies" width={500} height={300} />
                </div>
              </div>
            </div>
          </Carousel.Item>
        </Carousel>
        <section className="mt-8">
          <div className="container mx-auto">
            <h1>Watch Show Movies</h1>
          </div>
        </section>
      </Layouts>
    </div>
  );
}
